dist: trusty
sudo: required 
language: cpp

services:
  - docker

addons:
  apt:
    packages:
    - uuid-runtime
    - lcov
    - protobuf-compiler
    - libprotobuf-dev
    - libboost-system-dev
    - libboost-program-options-dev
    - libboost-thread-dev
  coverity_scan:
    project:
      name: "noahdesu/zlog"
      description: "Build submitted via Travis CI"
    notification_email: noahwatkins@gmail.com
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: coverity_scan

cache:
  ccache: true
  directories:
    - $HOME/zlog_ceph_deps

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EhSojL5dZ7LY9S59Iixzw8KUtMqVdE8dZTZqZ0gnA1VfG4XcQr8u8Vi9jJzGaGxcXIL10p3nE4whrmhlEhUpxKkrcOgKo9vKmn9xByUHd0CBhBudZAdlQsq4DMEp20qAwg+5iuCUHS6cn3UjduQqdo9YMhfqFuRiH+U3oZxS0W4="

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
      env: RUN_COVERAGE=1

before_install:
  - test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
  - ci/before_install.sh

script:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - ci/script.sh

after_success:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - ci/after_success.sh
